INCLUDE(LibFindMacros)

LIBFIND_PKG_CHECK_MODULES(HWLOC_PKGCONF hwloc)

FIND_PATH(HWLOC_INCLUDE_DIR
  NAMES hwloc.h
  PATHS ${HWLOC_PKGCONF_INCLUDE_DIRS}
)

FIND_LIBRARY(HWLOC_LIBRARY
  NAMES hwloc
  PATHS ${HWLOC_PKGCONF_LIBRARY_DIRS}
)

SET(HWLOC_PROCESS_INCLUDES HWLOC_INCLUDE_DIR)
SET(HWLOC_PROCESS_LIBS HWLOC_LIBRARY)
LIBFIND_PROCESS(HWLOC)
